version: "3.9"

services:
  postgres:
    image: postgres:15.1-alpine
    volumes:
      - ./backend/data/postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./backend/accounts/.env

  accounts:
    build:
      context: ./backend/accounts/
      dockerfile: ./build/Dockerfile
    volumes:
      - ./backend/accounts:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/accounts/.env
    depends_on:
      - postgres