version: "3.9"

services:
  db:
    image: postgres:15.1
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - backend/.env

  backend:
    build:
      context: backend
      dockerfile: ./build/Dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - db