version: "3.9"

services:
  postgres:
    image: postgres:15.1-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - accounts/.env

  accounts:
    build:
      context: accounts
      dockerfile: ./build/Dockerfile
    volumes:
      - ./accounts:/backend
    ports:
      - "8000:8000"
    env_file:
      - accounts/.env
    depends_on:
      - postgres