"""fix missing foreign key

Revision ID: e63c62922661
Revises: c3e133152f66
Create Date: 2023-02-18 10:15:35.497296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63c62922661'
down_revision = 'c3e133152f66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configurations', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'configurations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'configurations', type_='foreignkey')
    op.drop_column('configurations', 'user_id')
    # ### end Alembic commands ###
