"""add name to configuration table

Revision ID: 60ac0ac5a418
Revises: e93b3935f653
Create Date: 2023-05-30 17:47:06.828572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ac0ac5a418'
down_revision = 'e93b3935f653'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configurations', sa.Column('name', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configurations', 'name')
    # ### end Alembic commands ###
