"""add configurations table

Revision ID: c3e133152f66
Revises: 1598d0e7acc3
Create Date: 2023-02-18 10:05:56.028972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c3e133152f66"
down_revision = "1598d0e7acc3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configurations",
        sa.Column(
            "cloud_type",
            sa.Enum("AWS", "AZURE", "GCP", name="cloudtypeenum"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_configurations_id"), "configurations", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_configurations_id"), table_name="configurations")
    op.drop_table("configurations")
    # ### end Alembic commands ###
