"""add provider table and relations

Revision ID: e93b3935f653
Revises: e63c62922661
Create Date: 2023-04-03 11:49:40.285519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93b3935f653'
down_revision = 'e63c62922661'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_providers_id'), 'providers', ['id'], unique=False)
    op.add_column('configurations', sa.Column('provider_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'configurations', 'providers', ['provider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'configurations', type_='foreignkey')
    op.drop_column('configurations', 'provider_id')
    op.drop_index(op.f('ix_providers_id'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
